name: volpt_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.9.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  supabase_flutter: ^2.10.3
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  html: ^0.15.4
  flutter_map: ^8.2.2
  latlong2: ^0.9.1

  flutter_bloc: ^8.1.0
  equatable: ^2.0.5

   

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
